// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jbBsTsAVZv4BqgIPXg17_3imOgZ4qbs',
    appId: '1:347373334103:web:f0b7454a04beff759dbd12',
    messagingSenderId: '347373334103',
    projectId: 'kenorider-420a2',
    authDomain: 'kenorider-420a2.firebaseapp.com',
    storageBucket: 'kenorider-420a2.appspot.com',
    measurementId: 'G-R6M8HJV83X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAir7z8tZl3QU5771NbaZqhF6_PhZE18Xc',
    appId: '1:962647790880:android:9955e3f8b1fae9c0f7f345',
    messagingSenderId: '962647790880',
    projectId: 'kenoride-74b84',
    storageBucket: 'kenoride-74b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAir7z8tZl3QU5771NbaZqhF6_PhZE18Xc',
    appId: '1:962647790880:ios:dcecb0aff112917ef7f345',
    messagingSenderId: '962647790880',
    projectId: 'kenoride-74b84',
    storageBucket: 'kenoride-74b84.appspot.com',
    iosBundleId: 'com.kenora.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAC1EOIrTF9yjhBl5Db9W4zMk94_5sSu8',
    appId: '1:347373334103:ios:dc013afb379d56409dbd12',
    messagingSenderId: '347373334103',
    projectId: 'kenorider-420a2',
    storageBucket: 'kenorider-420a2.appspot.com',
    iosBundleId: 'com.uber.kenoriderDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3jbBsTsAVZv4BqgIPXg17_3imOgZ4qbs',
    appId: '1:347373334103:web:acb61989aa05f41f9dbd12',
    messagingSenderId: '347373334103',
    projectId: 'kenorider-420a2',
    authDomain: 'kenorider-420a2.firebaseapp.com',
    storageBucket: 'kenorider-420a2.appspot.com',
    measurementId: 'G-CFN54JNZED',
  );
}
